export const IS_READY_OVER_MENU_LETTERS = 'IS_READY_OVER_MENU_LETTERS';
export const MENU_LOGO_ANIMATION_IN = 'MENU_LOGO_ANIMATION_IN';
export const MENU_LOGO_ANIMATION_OUT = 'MENU_LOGO_ANIMATION_OUT';
