// GLOBAL ACTIONS
export const SET_END_FIRST_USER_TIME = 'SET_END_FIRST_USER_TIME';

// MENU LETTERS ACTIONS
export const ACTIVE_OVER_MENU_LETTERS = 'ACTIVE_OVER_MENU_LETTERS';
export const DESACTIVE_OVER_MENU_LETTERS = 'DESACTIVE_OVER_MENU_LETTERS';
export const SET_DIRECTION_IN_MENU_LETTERS = 'SET_DIRECTION_IN_MENU_LETTERS';
export const SET_DIRECTION_OUT_MENU_LETTERS = 'SET_DIRECTION_OUT_MENU_LETTERS';

// MENU LOGO ACTIONS
export const MENU_LOGO_ANIMATION_MOUSE_OVER = 'MENU_LOGO_ANIMATION_MOUSE_OVER';
export const MENU_LOGO_ANIMATION_MOUSE_OUT = 'MENU_LOGO_ANIMATION_MOUSE_OUT';

// MENU ACTIONS
export const SET_ACTIVE_SUPERHERO_MENU = 'SET_ACTIVE_SUPERHERO_MENU';
