// MENU ACTIONS
export const SET_ACTIVE_SUPERHERO = 'SET_ACTIVE_SUPERHERO';
export const SET_CURRENT_SUPERHERO_COUNTER = 'SET_CURRENT_SUPERHERO_COUNTER';
export const SET_MENU_DIRECTION = 'SET_MENU_DIRECTION';
