export const ACTIVE_OVER_MENU_LETTERS = 'ACTIVE_OVER_MENU_LETTERS';
export const DESACTIVE_OVER_MENU_LETTERS = 'DESACTIVE_OVER_MENU_LETTERS';
export const MENU_LOGO_ANIMATION_IN = 'MENU_LOGO_ANIMATION_IN';
export const MENU_LOGO_ANIMATION_OUT = 'MENU_LOGO_ANIMATION_OUT';
